// <auto-generated />
using System;
using GPLX.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GPLX.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GPLX.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GPLX.Models.CongDan", b =>
                {
                    b.Property<string>("Cccd")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("CCCD")
                        .IsFixedLength();

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("QuocTich")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Việt Nam");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Cccd")
                        .HasName("PK__CongDan__A955A0ABA6F2BB53");

                    b.ToTable("CongDan", (string)null);
                });

            modelBuilder.Entity("GPLX.Models.DangKyKhoaHoc", b =>
                {
                    b.Property<int>("MaDkkh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDKKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDkkh"));

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("CCCD")
                        .IsFixedLength();

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThaiDangKy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Đã đăng ký");

                    b.HasKey("MaDkkh")
                        .HasName("PK__DangKyKh__3D7B8BC80A52B26B");

                    b.HasIndex("MaLop");

                    b.HasIndex(new[] { "Cccd", "MaLop" }, "UQ_DKKH")
                        .IsUnique();

                    b.ToTable("DangKyKhoaHoc", (string)null);
                });

            modelBuilder.Entity("GPLX.Models.DieuKienDatGplx", b =>
                {
                    b.Property<int>("MaDkdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDKDat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDkdat"));

                    b.Property<int?>("DiemDuongTruongDat")
                        .HasColumnType("int");

                    b.Property<int>("DiemLyThuyetDat")
                        .HasColumnType("int");

                    b.Property<int?>("DiemMoPhongDat")
                        .HasColumnType("int");

                    b.Property<int>("DiemThucHanhDat")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.HasKey("MaDkdat")
                        .HasName("PK__DieuKien__DC4946A7478CDB2E");

                    b.HasIndex("MaLoai");

                    b.ToTable("DieuKienDatGPLX", (string)null);
                });

            modelBuilder.Entity("GPLX.Models.DkthiGplx", b =>
                {
                    b.Property<int>("MaDkthiGplx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDKThiGPLX");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDkthiGplx"));

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("CCCD")
                        .IsFixedLength();

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<int>("MaTtsh")
                        .HasColumnType("int")
                        .HasColumnName("MaTTSH");

                    b.Property<DateOnly>("NgayThi")
                        .HasColumnType("date");

                    b.HasKey("MaDkthiGplx")
                        .HasName("PK__DKThiGPL__FA64BE89BE9D1072");

                    b.HasIndex("Cccd");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaTtsh");

                    b.ToTable("DKThiGPLX", null, t =>
                        {
                            t.HasTrigger("trg_Check_DoTuoi_DKThi");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("GPLX.Models.GiangVien", b =>
                {
                    b.Property<int>("MaGv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGv"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.HasKey("MaGv")
                        .HasName("PK__GiangVie__2725AEF3283B4BDF");

                    b.ToTable("GiangVien", (string)null);
                });

            modelBuilder.Entity("GPLX.Models.Gplx", b =>
                {
                    b.Property<string>("MaGplx")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("MaGPLX")
                        .IsFixedLength();

                    b.Property<string>("MaKetQua")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)");

                    b.Property<DateOnly>("NgayCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("NgayHetHan")
                        .HasColumnType("date");

                    b.HasKey("MaGplx")
                        .HasName("PK__GPLX__674D12528C5CD04C");

                    b.HasIndex("MaKetQua");

                    b.ToTable("GPLX", null, t =>
                        {
                            t.HasTrigger("trg_Check_KetQuaDat_GPLX");

                            t.HasTrigger("trg_Check_NgayCap_GPLX");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("GPLX.Models.KetQuaThiGplx", b =>
                {
                    b.Property<string>("MaKetQua")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)");

                    b.Property<int?>("DiemDuongTruong")
                        .HasColumnType("int");

                    b.Property<int>("DiemLyThuyet")
                        .HasColumnType("int");

                    b.Property<int?>("DiemMoPhong")
                        .HasColumnType("int");

                    b.Property<int>("DiemThucHanh")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaDkthiGplx")
                        .HasColumnType("int")
                        .HasColumnName("MaDKThiGPLX");

                    b.HasKey("MaKetQua")
                        .HasName("PK__KetQuaTh__D5B3102A1D520BF1");

                    b.HasIndex(new[] { "MaDkthiGplx" }, "UQ__KetQuaTh__FA64BE8871E65C42")
                        .IsUnique();

                    b.ToTable("KetQuaThiGPLX", (string)null);
                });

            modelBuilder.Entity("GPLX.Models.KhoaHoc", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThoiGianHoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKhoaHoc")
                        .HasName("PK__KhoaHoc__48F0FF98C46C293E");

                    b.ToTable("KhoaHoc", (string)null);
                });

            modelBuilder.Entity("GPLX.Models.LoaiGplx", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<byte>("DoTuoiDuocCap")
                        .HasColumnType("tinyint");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai")
                        .HasName("PK__LoaiGPLX__730A5759C368576A");

                    b.ToTable("LoaiGPLX", (string)null);
                });

            modelBuilder.Entity("GPLX.Models.LoaiViPham", b =>
                {
                    b.Property<int>("MaLoaiViPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiViPham"));

                    b.Property<decimal>("MucPhat")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TenViPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaLoaiViPham")
                        .HasName("PK__LoaiViPh__760D02765ED60D6E");

                    b.ToTable("LoaiViPham", (string)null);
                });

            modelBuilder.Entity("GPLX.Models.LopHoc", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MaGv")
                        .HasColumnType("int")
                        .HasColumnName("MaGV");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("ThoiGianHocTrongTuan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Đang mở");

                    b.HasKey("MaLop")
                        .HasName("PK__LopHoc__3B98D2737111EEC7");

                    b.HasIndex("MaGv");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("LopHoc", (string)null);
                });

            modelBuilder.Entity("GPLX.Models.TrungTamSatHach", b =>
                {
                    b.Property<int>("MaTtsh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTTSH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTtsh"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoDt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SoDT");

                    b.Property<string>("TenTrungTam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTtsh")
                        .HasName("PK__TrungTam__4484222233F6EEA2");

                    b.ToTable("TrungTamSatHach", (string)null);
                });

            modelBuilder.Entity("GPLX.Models.ViPhamGplx", b =>
                {
                    b.Property<int>("MaViPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaViPham"));

                    b.Property<string>("MaGplx")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("MaGPLX")
                        .IsFixedLength();

                    b.Property<int>("MaLoaiViPham")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayViPham")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chưa đóng phạt");

                    b.HasKey("MaViPham")
                        .HasName("PK__ViPhamGP__F1921D8999C9A02F");

                    b.HasIndex("MaGplx");

                    b.HasIndex("MaLoaiViPham");

                    b.ToTable("ViPhamGPLX", null, t =>
                        {
                            t.HasTrigger("trg_Check_NgayViPham");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GPLX.Models.DangKyKhoaHoc", b =>
                {
                    b.HasOne("GPLX.Models.LopHoc", "MaLopNavigation")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("MaLop")
                        .IsRequired()
                        .HasConstraintName("FK_DKKH_LopHoc");

                    b.Navigation("MaLopNavigation");
                });

            modelBuilder.Entity("GPLX.Models.DieuKienDatGplx", b =>
                {
                    b.HasOne("GPLX.Models.LoaiGplx", "MaLoaiNavigation")
                        .WithMany("DieuKienDatGplxes")
                        .HasForeignKey("MaLoai")
                        .IsRequired()
                        .HasConstraintName("FK_DieuKienDat_LoaiGPLX");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("GPLX.Models.DkthiGplx", b =>
                {
                    b.HasOne("GPLX.Models.CongDan", "CccdNavigation")
                        .WithMany("DkthiGplxes")
                        .HasForeignKey("Cccd")
                        .IsRequired()
                        .HasConstraintName("FK_DKThi_CCCD");

                    b.HasOne("GPLX.Models.LoaiGplx", "MaLoaiNavigation")
                        .WithMany("DkthiGplxes")
                        .HasForeignKey("MaLoai")
                        .IsRequired()
                        .HasConstraintName("FK_DKThi_LoaiGPLX");

                    b.HasOne("GPLX.Models.TrungTamSatHach", "MaTtshNavigation")
                        .WithMany("DkthiGplxes")
                        .HasForeignKey("MaTtsh")
                        .IsRequired()
                        .HasConstraintName("FK_DKThi_TTSH");

                    b.Navigation("CccdNavigation");

                    b.Navigation("MaLoaiNavigation");

                    b.Navigation("MaTtshNavigation");
                });

            modelBuilder.Entity("GPLX.Models.Gplx", b =>
                {
                    b.HasOne("GPLX.Models.KetQuaThiGplx", "MaKetQuaNavigation")
                        .WithMany("Gplxes")
                        .HasForeignKey("MaKetQua")
                        .IsRequired()
                        .HasConstraintName("FK_GPLX_KetQuaThiGPLX");

                    b.Navigation("MaKetQuaNavigation");
                });

            modelBuilder.Entity("GPLX.Models.KetQuaThiGplx", b =>
                {
                    b.HasOne("GPLX.Models.DkthiGplx", "MaDkthiGplxNavigation")
                        .WithOne("KetQuaThiGplx")
                        .HasForeignKey("GPLX.Models.KetQuaThiGplx", "MaDkthiGplx")
                        .IsRequired()
                        .HasConstraintName("FK_KetQua_DKThi");

                    b.Navigation("MaDkthiGplxNavigation");
                });

            modelBuilder.Entity("GPLX.Models.LopHoc", b =>
                {
                    b.HasOne("GPLX.Models.GiangVien", "MaGvNavigation")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaGv")
                        .IsRequired()
                        .HasConstraintName("FK_Lop_GiangVien");

                    b.HasOne("GPLX.Models.KhoaHoc", "MaKhoaHocNavigation")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaKhoaHoc")
                        .IsRequired()
                        .HasConstraintName("FK_Lop_KhoaHoc");

                    b.Navigation("MaGvNavigation");

                    b.Navigation("MaKhoaHocNavigation");
                });

            modelBuilder.Entity("GPLX.Models.ViPhamGplx", b =>
                {
                    b.HasOne("GPLX.Models.Gplx", "MaGplxNavigation")
                        .WithMany("ViPhamGplxes")
                        .HasForeignKey("MaGplx")
                        .IsRequired()
                        .HasConstraintName("FK_ViPham_GPLX");

                    b.HasOne("GPLX.Models.LoaiViPham", "MaLoaiViPhamNavigation")
                        .WithMany("ViPhamGplxes")
                        .HasForeignKey("MaLoaiViPham")
                        .IsRequired()
                        .HasConstraintName("FK_ViPham_LoaiViPham");

                    b.Navigation("MaGplxNavigation");

                    b.Navigation("MaLoaiViPhamNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GPLX.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GPLX.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPLX.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GPLX.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GPLX.Models.CongDan", b =>
                {
                    b.Navigation("DkthiGplxes");
                });

            modelBuilder.Entity("GPLX.Models.DkthiGplx", b =>
                {
                    b.Navigation("KetQuaThiGplx");
                });

            modelBuilder.Entity("GPLX.Models.GiangVien", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("GPLX.Models.Gplx", b =>
                {
                    b.Navigation("ViPhamGplxes");
                });

            modelBuilder.Entity("GPLX.Models.KetQuaThiGplx", b =>
                {
                    b.Navigation("Gplxes");
                });

            modelBuilder.Entity("GPLX.Models.KhoaHoc", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("GPLX.Models.LoaiGplx", b =>
                {
                    b.Navigation("DieuKienDatGplxes");

                    b.Navigation("DkthiGplxes");
                });

            modelBuilder.Entity("GPLX.Models.LoaiViPham", b =>
                {
                    b.Navigation("ViPhamGplxes");
                });

            modelBuilder.Entity("GPLX.Models.LopHoc", b =>
                {
                    b.Navigation("DangKyKhoaHocs");
                });

            modelBuilder.Entity("GPLX.Models.TrungTamSatHach", b =>
                {
                    b.Navigation("DkthiGplxes");
                });
#pragma warning restore 612, 618
        }
    }
}
